# This Is Our 2nd Project, Where We Create A Game Which Is Guess The Number.

# Rules.
# --> Guess A Number Which Is Generated By Computer.
# --> Count The Number Of Guesses Taken By The User As An Attempt.
# --> Give Hint, Like Number Is Lesser Or Higher.
# --> Any User Who Takes Lesser Number Of Attempts Then That Will Win. 
# --> For Error We Take Care Of Error Handling (Not Necessary)

# Importing Required Modules.
import random

# Welcoming The User.
print("")
print(f"Welcome To, Guess The Number Game.")
print(f"Let's Play ......\n")

try:
    number = random.randint(1,50)
    # print(number) # Only For Checking Purpose 

    attempts = 1
    userNumber = -1

    while(number != userNumber):
        userNumber = int(input("Guess The Number Out Of (50): "))

        if(userNumber > number):
            print(f"Number Is Bigger.....")
            attempts += 1

        elif(userNumber < number):
            print(f"Number Is Lesser.....")
            attempts += 1

    print(f"You, Successfully Guess The Number {number} Which Is Generated By Computer In {attempts} Attempts.")

except ValueError as vr:
    print(vr)
    print("Please, Restart The Games For Play Again.....")

# We Nailed It, Here We Successfully Created A Game Which Is Guessing The Number Generated Computer.